MODEL:
  META_ARCHITECTURE: "BlendMask"
  MASK_ON: True
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, True, True, True]
    DEFORM_MODULATED: True
    DEFORM_INTERVAL: 3
    OUT_FEATURES: ["res3", "res4", "res5"]
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  BASIS_MODULE:
    LOSS_ON: True
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: False
  FCOS:
    THRESH_WITH_CTR: True
    USE_SCALE: False
DATASETS:
  TRAIN: ("xray_4classes_train",)
  TEST: ("xray_4classes_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (280000, 360000)
  MAX_ITER: 400000
INPUT:
  MIN_SIZE_TRAIN: (640, 864)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 1440
  CROP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 20000
OUTPUT_DIR: "/data2/blendmask_output/UML_Peru_4classes_0004"
